DELETE http://localhost:3003/api/blogs/698af369fce6a23befad92c1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjY5OGFmMjg0ZmNlNmEyM2JlZmFkOTJiOSIsImlhdCI6MTc3MDgwMjcyOCwiZXhwIjoxNzcwODA5OTI4fQ.VgbJNIIARnqJamDWNDB3vLQMnBGUM8JJmrDDugJk0X4